### ISSUE TITLE
Incorrect file paths

### ISSUE THREAD

**Issue by AlecSPb** [webeks/code200-eucookielawmadness#1]
After installing the plugin, path for loading CSS and JS files incorrect:

``` html
<link rel="stylesheet" href="http://domain.com/themes/demo/plugins/code200/eucookielawmadness/assets/cookieconsent.min.css">
<script src="http://domain.com/themes/demo/plugins/code200/eucookielawmadness/assets/cookieconsent.min.js"></script>
```

It would be more correct way:

``` html
<link rel="stylesheet" href="http://domain.com/plugins/code200/eucookielawmadness/assets/cookieconsent.min.css">
<script src="http://domain.com/plugins/code200/eucookielawmadness/assets/cookieconsent.min.js"></script>
```

**Comment by webeks** [comment]
Thanks for feedback. 

I checked my local demo and I cant replicate the problem. 
In the code CSS and JS are called inside plugins/Code200/eucookielawmadness/Plugin.php
[L31](https://github.com/webeks/code200-eucookielawmadness/blob/master/Plugin.php#L31) and path is set on [L23](https://github.com/webeks/code200-eucookielawmadness/blob/master/Plugin.php#L23)

Could you please check if you are running latest version of OctoberCMS and that you have set APP_URL in your config?

**Comment by webeks** [comment]
@AlecSPB paths were changed in commit https://github.com/webeks/code200-eucookielawmadness/commit/3a41e524ccda3a01a6ea27fcff76ecfb5a38f919 made by @gergo85 

If this doesnt help please open new bug report with more details. Thanks, Miha
